apiVersion: v1
kind: Pod
metadata:
  generateName: stats-logs-inspector
spec:
  containers:
  - args:
    - bash
    image: debian:11
    name: bash
    stdin: true
    stdinOnce: true
    tty: true
    workingDir: /data
    volumeMounts:
    - mountPath: /data
      name: datadir
      readOnly: true
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: stats-logs-collector-data-dir-claim
