apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmi-stat-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vmi-stat-collector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmi-stat-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vmi-stat-collector
subjects:
- kind: ServiceAccount
  name: vmi-stat-collector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: vmi-stat-collector
    app.kubernetes.io/managed-by: vmi-stat-collector
    app: vmi-stat-collector
  name: vmi-stat-collector
spec:
  ports:
  - port: 8099
    protocol: TCP
    targetPort: 8099
  selector:
    app: vmi-stat-collector
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmi-stat-collector-data-dir-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmi-stat-collector
  labels:
    app: vmi-stat-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmi-stat-collector
  template:
    metadata:
      labels:
        app: vmi-stat-collector
    spec:
      serviceAccountName: vmi-stat-collector
      containers:
      - name: memstats
        image: quay.io/acardace/stat-collector:latest
        env:
        - name: DATA_DIR
          value: /data
        - name: HTTP_PORT
          value: "8099"
        ports:
        - containerPort: 8099
        volumeMounts:
        - name: datadir
          mountPath: /data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: vmi-stat-collector-data-dir-claim


