apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmi-stat-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vmi-stat-collector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmi-stat-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vmi-stat-collector
subjects:
- kind: ServiceAccount
  name: vmi-stat-collector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: stats-logs-collector
    app.kubernetes.io/managed-by: stats-logs-collector
    app: stats-logs-collector
  name: stats-logs-collector
spec:
  ports:
  - port: 8099
    protocol: TCP
    targetPort: 8099
  selector:
    app: stats-logs-collector


