apiVersion: v1
kind: ServiceAccount
metadata:
  name: logs-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logs-collector
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/portforward
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - kubevirt.io
    resources:
      - kubevirts
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - hco.kubevirt.io
    resources:
      - hco
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstances
      - virtualmachines
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logs-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logs-collector
subjects:
  - kind: ServiceAccount
    name: logs-collector
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-collector-data-dir-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-collector
  labels:
    app: logs-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-collector
  template:
    metadata:
      labels:
        app: logs-collector
    spec:
      serviceAccountName: logs-collector
      containers:
        - name: logs-collector
          image: quay.io/ffossemo/logs-collector:latest
          env:
            - name: DATA_DIR
              value: /data
          volumeMounts:
            - name: datadir
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: logs-collector-data-dir-claim